version: "2"

services:
  bitmex-delta-server:
    container_name: bitmex-delta-server
    build: 
      context: .
    environment:
      - DEBUG=BitMEX:* node index.js
      - PORT=4444
      - IS_TESTNET=true
      - SYMBOL=XBTUSD
      - STREAMS=orderBook10 # https://www.bitmex.com/app/wsAPI#Subscriptions
      # - BITMEX_KEY= # assuming set BITMEX_KEY in .env, TEST_BITMEX_KEY as well
      # - BITMEX_SECRET_KEY= # assuming set BITMEX_SECRET_KEY in .env, TEST_BITMEX_SECRET_KEY as well
      - MAX_TABLE_LEN=5000
    env_file: .env
    ports:
      - "4444:4444"
