#!/bin/bash
if [ -z "$IS_TESTNET" ]; then
  echo "Environment variable 'IS_TESTNET' is empty!"
  exit 1
fi
if [ -z "$PORT" ]; then
  echo "Environment variable 'PORT' is empty!"
  exit 1
fi
if [ -z "$SYMBOL" ]; then
  echo "Environment variable 'SYMBOL' is empty!"
  exit 1
fi
if [ -z "$STREAMS" ]; then
  echo "Environment variable 'STREAMS' is empty!"
  exit 1
fi
if [ -z "$MAX_TABLE_LEN" ]; then
  echo "Environment variable 'MAX_TABLE_LEN' is empty!"
  exit 1
fi

if "$IS_TESTNET" = "true"; then
  export BITMEX_KEY=$TEST_BITMEX_KEY
  export BITMEX_SECRET_KEY=$TEST_BITMEX_SECRET_KEY
fi

cat config.js.template | envsubst > config.js
